// src/vue/App.vue
<template lang="pug">
.container
        h2 Vue!
        h2 Let's Count! {{ counter }}
        ul
            li
                a(href="/index.html") Home
            li
                a(href="/react.html") Go to the React App...
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";

// Declare a reactive counter variable
const counter = ref(0);

// Use onMounted to set up the interval
onMounted(() => {
	setInterval(() => {
		counter.value++;
	}, 1000);
});
</script>

<style lang="stylus" scoped>
bgStyle = darkslategray
textStyle = aquamarine

.container
    display: flex
    align-items: center
    justify-content: center
    flex-direction: column
    width: 900px
    padding: 40px
    font-family: sans-serif
    background-color: bgStyle
    color: textStyle

    h2
        font-size: 64px

    a
        font-size: 28px
        color: mintcream
</style>

// src/react/App.tsx
import React, { useState } from "react";
import parcelLogo from "../images/image.png";
import styled from "styled-components";

const Container = styled.div`
	display: flex;
	flex-direction: column;
	place-items: center;
	background-color: midnightblue;
	color: cornflowerblue;
	font-family: sans-serif;
	width: 600px;
	padding: 40px;

	h2 {
		font-size: 50px;
	}

	a {
		font-size: 18px;
		color: #e3e3e3;
		margin-bottom: 2rem;
		text-decoration: none;
	}
`;

const App = () => {
	const [state, setState] = useState(false);
	return (
		<Container>
			<h2
				onClick={() => {
					setState(!state);
				}}
			>
				What is state?: {state.toString()};
			</h2>
			<a href="./index.html">Home</a>
			<a href="./vue.html">Go to the Vue App...</a>
			<img src={parcelLogo} alt="parcel bundler logo" width={400} />
		</Container>
	);
};

export default App;
